[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "9e36dce3acbc030b8f8a1ddf86c993d3ae5e03aa"
os = "macos"

    [[LibTeXPrintf.download]]
    sha256 = "86ca815f1a2dc8216c8468b4a4d48fc6fdf3fa8cd49e232f9c75b90bac22a89c"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.aarch64-apple-darwin.tar.gz"
[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "0678b6656c70a020563fdcbcaa29881fdaec9977"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "f3a9b59f7077257579da634239c4b2760a0cd0b6f6132bef367e892800df1f59"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.aarch64-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "566f3a2074a7e9de0a6d610195bf83070b8bc6f7"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "8775386cb1da6e19700c1ef136041c862afd92745b50cffa26909b92e90ab92c"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.aarch64-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "edc8c43115ff3b57e007ff2b1d808b0d2063469f"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "a86f400ff87db72707ca657ca994e8c99dbffb246306a24c68bc34e93fdb1f6e"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.armv6l-linux-gnueabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "709a37eacc9d258908ec05f0a043f09669a43950"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "974d932d56210fc2030c4c1d8ded084a1e79718cce365e97328621b29cbb7cc1"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.armv6l-linux-musleabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c419765cbf31958ddf79f01442d4436b77b6f9c0"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "a0ff626614a528ad6e6386e044846f7fd87840a1b28fb87151a13f2db2f4a710"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.armv7l-linux-gnueabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "def7813ab2e65342070138ce9613347fc0f289ba"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "bd94c5b00577658754491c1088c5534acb2077734f23973f88f803e409aa6861"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.armv7l-linux-musleabihf.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "fba607f7c66872bb46db1e279525533b110e2adf"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "961839b5d9121f4ac39d503bccbcac1ccfc9eb3940e1187273efb9444b500e95"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.i686-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "04a39b3262b97c887ff7c3fc9503cc5ce7fa6a13"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "b1e8f39e2a872288a634d38ea6eec6e600d005ee00afa45e019d9afd0353e0f1"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.i686-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "f4b1e0ae1ed352c471cd565d9bc4d43cb51f105d"
os = "windows"

    [[LibTeXPrintf.download]]
    sha256 = "6c3a8e0911c879eb7d9329279a54c78c0774d03c36d4ec95aa1c6a9698bc6ed6"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.i686-w64-mingw32.tar.gz"
[[LibTeXPrintf]]
arch = "powerpc64le"
git-tree-sha1 = "910cfb926f72a0d40ef1217e7767463693845582"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "37e78f90657bae62b986a52a1242b07f9e4969e9c2679d2340787e84e23030b9"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.powerpc64le-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "1660602eb338cdc702dfcd10ab18262dfe1e9b46"
os = "macos"

    [[LibTeXPrintf.download]]
    sha256 = "7fc5f09b51131c9c984451e5215fe418eca098e456a9b1dd68d31cc73b00c964"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.x86_64-apple-darwin.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "41ce71e6316ffd02ded66fe69800f6b1256f4078"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "23319400cf5b2d914f3565fb6462720774c18a0f87c128717bf7a5e07a3d9dd5"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.x86_64-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "be05f43e105431870ee8fdc280ba3d7d41da12e7"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "2867a2a0f1e5409bdebe7f7e649c5a12ead9f7c7a08dfa0b48cbdeb0603bf85d"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.x86_64-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "02fde00f25f6ffcfca5f40ec6af6c24d4fa9a709"
os = "freebsd"

    [[LibTeXPrintf.download]]
    sha256 = "501108605c9f672e51bfe472427db003d18f8895eea3adbed562950ae8fdad67"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.x86_64-unknown-freebsd.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "f81549bfd593f5ca5f14fa8118cd31534e8f210f"
os = "windows"

    [[LibTeXPrintf.download]]
    sha256 = "e76548acecf11eb4a4f25634e5e37bf6e5dbaa8be2539589c2583f45a271b248"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.2+0/LibTeXPrintf.v1.14.2.x86_64-w64-mingw32.tar.gz"
