[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "997c500d973e730021cc5cefac9823e64e0a00d7"
os = "macos"

    [[LibTeXPrintf.download]]
    sha256 = "7bce096e1b5b06853317518dc8737c422651301cf72dacb091ebbb29c27cfcee"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.aarch64-apple-darwin.tar.gz"
[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "7339c0009be988760fd62d604761b3443a4c139d"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "89b7e435b076fa63d225297ca2823ecaaf5f07158ef8a59a70d1d41f859b4ac5"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.aarch64-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "aarch64"
git-tree-sha1 = "f1b0f37168af452913b12722e5ca5623a2ec2ca3"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "ffebced5060f1070dc8f9a742716f514af37f593595de31690435b7fad48cff1"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.aarch64-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae4c4539ed20660f3bba3dd565b0ae1e88300f1c"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "173ed320ddd27519cc9cc4dfccc035ab789b4dfa827710de6604b7226a59a338"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.armv6l-linux-gnueabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "078cd8530648af6db0c674d906906a4d405cb146"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "17b34799c5c29e2ca0c6810ce23009a54f248e6b54e7abde8b0398fab39abf5b"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.armv6l-linux-musleabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c5aa6c9548213a2fbf6b02640a13903c4a42fcc"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "8f2bd37c707afa87bf5c159fc1d588c2ca14c2ea98582d77346826cb1c2c5c8b"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.armv7l-linux-gnueabihf.tar.gz"
[[LibTeXPrintf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fa581e9ac8d5b83540c5729d1631386740861e9"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "e057828f633114592e6a88d3a2368f6f1e6128b822073d700c8539f3e0f9abd3"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.armv7l-linux-musleabihf.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "d9c4059a96e02a3f670c557d5a58314f42a97ed3"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "949ac4324a36f0be1a39bb9515dc0afb14bfc44c7d4bb9202bff09fa2ec14fc7"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.i686-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "a6c5a48985f34fc8abdb8aa225a85c3d033e7b27"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "355a7c74ee2d8acd7759a524c3616e75544b699bb059ea29404ed880df1ee777"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.i686-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "i686"
git-tree-sha1 = "b1eba73dc0d2cc42d1d253768957375c95e884ba"
os = "windows"

    [[LibTeXPrintf.download]]
    sha256 = "8bed15b185359578c10523e45cac44104d0dbe8537b67458299302a24e4c290b"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.i686-w64-mingw32.tar.gz"
[[LibTeXPrintf]]
arch = "powerpc64le"
git-tree-sha1 = "6f35ac7d940275ea7c30f0025fc5e286109aab45"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "b5794149b86db02a155384b5ec64937aef81111cb61987f7dab75db8bdbd0b90"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.powerpc64le-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "2d0e8fe7a726e90f97a879903f8f3808c1e4c643"
os = "macos"

    [[LibTeXPrintf.download]]
    sha256 = "e6cf2bfb599d3e4dc4bf305016a39edd5f854def3313c266d8073028da48ce3b"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.x86_64-apple-darwin.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "8ae08b05ee90f9404b8eb41c861efdf49e6052e5"
libc = "glibc"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "0fe78c740e4a52260bdbd89edfb1da2920e80f4702e93cb13ea099e012d6a1b5"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.x86_64-linux-gnu.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "a5fc06762434a18ac0d66c7bf4acfee95e80f3b4"
libc = "musl"
os = "linux"

    [[LibTeXPrintf.download]]
    sha256 = "17822a91ff6074601f9ef28ccef35a6c8d91415bbfa36d872367ad918a5a7f50"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.x86_64-linux-musl.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "a9056b107f32290fa4ae69373435a6f5e696b986"
os = "freebsd"

    [[LibTeXPrintf.download]]
    sha256 = "e03b71e8467060eed9a968bfe93da7fd0ad3b87f523fa6cf0cbc0fd3e78dab7d"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.x86_64-unknown-freebsd.tar.gz"
[[LibTeXPrintf]]
arch = "x86_64"
git-tree-sha1 = "5ca3aab549cffff6f205a7ee45a035507e663069"
os = "windows"

    [[LibTeXPrintf.download]]
    sha256 = "3268609c8964c421109300c16ee2a081ea0047de6a8a2139d84448d526281ab9"
    url = "https://github.com/JuliaBinaryWrappers/LibTeXPrintf_jll.jl/releases/download/LibTeXPrintf-v1.14.1+0/LibTeXPrintf.v1.14.1.x86_64-w64-mingw32.tar.gz"
