# Autogenerated wrapper script for LibTeXPrintf_jll for aarch64-apple-darwin
export libtexprintf

JLLWrappers.@generate_wrapper_header("LibTeXPrintf")
JLLWrappers.@declare_library_product(libtexprintf, "@rpath/libtexprintf.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtexprintf,
        "lib/libtexprintf.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
