# Autogenerated wrapper script for LibTeXPrintf_jll for i686-w64-mingw32
export libtexprintf

JLLWrappers.@generate_wrapper_header("LibTeXPrintf")
JLLWrappers.@declare_library_product(libtexprintf, "libtexprintf-1.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtexprintf,
        "bin\\libtexprintf-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
